### ISSUE TITLE
box leaks memory

### ISSUE THREAD

**Issue by andrewchambers** [ahungry/janet-pobox#2]
it seems you never call free on the buffers you malloc, even when reassigning them.

**Comment by ahungry** [comment]
Doh!  Thanks, I should probably fix that up

**Comment by ahungry** [comment]
buffer_to_bytes char * buffers are now freed in 5936dbc and updating an existing key now frees old allocation before making new one in d0998df

I think this frees everything that is freeable, since the other malloc calls have to deal with the "office" itself, which is never intended to go away (if you have the time/inclination, please re-review/open this if you find otherwise :) )
